# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Machine Learning and the Physical World
author:
  name: Neil D. Lawrence
  email:
  twitter: lawrennd
description: >- # this means to ignore newlines until "baseurl:"
  This is the website of the Machine Learning and the Physical World module
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/mlphysical" # the subpath of your site, e.g. /blog
twitter_username:
github_username: mlatcl
colab: https://colab.research.google.com
nbviewer: https://nbviewer.jupyter.org

slidesdir: slides
reveal:
  width: 512
  height: 384
youtube:
  width: 512
  height: 384

collections:
  updates:
    output: true
  lectures:
    permalink: /lectures/:title:output_ext
    output: true
    sort_by: week
  special_topics:
    permalink: /special_topics/:title:output_ext
    output: true
    sort_by: label
  practicals:
    permalink: /practicals/:title:output_ext
    output: true
    sort_by: week

ghub:
  edit: true
  repository: mlphysical

analytics:
  google: 
    tracking_id: UA-184894912-1
  
# Build settings
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - slides/reveal.js/examples/
  - slides/reveal.js/test/
  - slides/reveal.js/css/theme
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

future: true
