author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
room: LT2
venue: William Gates Building
talkcss: https://inverseprobability.com/assets/css/talks.css
bibdir: $HOME/lawrennd/bibliography/
postsdir: ../_lectures/
slidesdir: ../slides/
notesdir: ../_notes/
notebooksdir: ../_notebooks/
practicalsdir: ../_practicals/
snippetsdir: $HOME/lawrennd/snippets/
writediagramsdir: .
scriptsdir: ./scripts/
diagramsdir: ./slides/diagrams/
transition: None
baseurl: "mlphysical/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.io/" # the base hostname & protocol for your site
ghub:
- organization: mlatcl
  repository: mlphysical
  branch: gh-pages
  directory: _lamd
transition: None
  
